# Generated by Django 2.2.3 on 2019-07-31 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('term', models.CharField(max_length=20)),
                ('classRoom', models.CharField(max_length=20)),
                ('termNumber', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('finishDate', models.DateField()),
                ('days', models.CharField(max_length=100)),
                ('startTime', models.TimeField()),
                ('finishTime', models.TimeField()),
                ('paymentTerm', models.IntegerField(max_length=10)),
                ('paymentBook', models.BigIntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='insitute',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('fatherName', models.CharField(max_length=20)),
                ('nationalCode', models.BigIntegerField(
                    max_length=10, unique=True)),
                ('teacherNumber', models.AutoField(
                    primary_key=True, serialize=False)),
                ('birthday', models.DateField()),
                ('homeNumber', models.BigIntegerField(max_length=11)),
                ('cellphoneNumber', models.BigIntegerField(max_length=11)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField()),
                ('image', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('fatherName', models.CharField(max_length=20)),
                ('nationalCode', models.BigIntegerField(
                    max_length=10, unique=True)),
                ('studentNumber', models.AutoField(
                    primary_key=True, serialize=False)),
                ('birthday', models.DateField()),
                ('homeNumber', models.BigIntegerField(max_length=11)),
                ('cellphoneNumber', models.BigIntegerField(max_length=11)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField()),
                ('image', models.ImageField(blank=True, upload_to='image')),
                ('paymentTerm', models.IntegerField(max_length=10)),
                ('paymentBook', models.BigIntegerField(max_length=10)),
                ('paymentState',  models.CharField(max_length=20)),
                ('termNumber', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='myInstitute.classes')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='teacherNumber',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='myInstitute.teacher'),
        ),
    ]
